# Generated by Django 2.2 on 2019-04-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='modelYear',
            field=models.IntegerField(),
        ),
    ]
