# Generated by Django 2.2 on 2019-04-29 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('techs', '0003_auto_20190429_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makerName', models.CharField(max_length=100)),
                ('makerOwner', models.CharField(max_length=200)),
                ('makerLogo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CarYard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yardName', models.CharField(max_length=100)),
                ('yardPhone', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=100)),
                ('modelYear', models.IntegerField()),
                ('modelOwner', models.CharField(max_length=100)),
                ('modelMaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.CarMaker')),
            ],
        ),
    ]
