# Generated by Django 2.2 on 2019-04-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0004_carmaker_carmodel_caryard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmaker',
            name='makerLogo',
            field=models.ImageField(upload_to='car_maker/'),
        ),
    ]
