# Generated by Django 2.2 on 2019-04-29 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('techs', '0005_auto_20190429_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarYard',
            new_name='Yard',
        ),
        migrations.CreateModel(
            name='YardCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.CarModel')),
                ('yardName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.Yard')),
            ],
        ),
    ]
