# Generated by Django 2.2 on 2019-04-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0006_auto_20190429_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YardCars',
            new_name='YardCar',
        ),
    ]
