# Generated by Django 2.2 on 2019-04-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0007_auto_20190429_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsInYard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfYard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.Yard')),
                ('carName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.CarModel')),
            ],
        ),
        migrations.DeleteModel(
            name='YardCar',
        ),
    ]
