# Generated by Django 2.2 on 2019-05-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0008_auto_20190429_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='color',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(default=1000000),
        ),
    ]
